name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Копирование .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
    - name: Установка зависимостей
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Генерация ключа
      run: php artisan key:generate
    - name: Настройка разрешений для директорий
      run: chmod -R 777 storage bootstrap/cache
    - name: Build assets
      run: npm ci && npm run build
    - name: Create databases
      run: |
        touch testbench.sqlite
        mysql -e 'CREATE DATABASE testbench' -h127.0.0.1 -uroot -ppassword -P ${{ job.services.mysql.ports[3306] }}  
    - name: Запуск тестов (Unit и Feature тесты) с помощью PHPUnit
      run: vendor/bin/phpunit --testdox --testsuite feature
      env:
        APP_KEY: base64:Y+pIAj02q1T2gH21udzlJkIafG20HoNp55c/8vBKlOk=
        DB_CONNECTION: mysql
        DB_DATABASE: db_test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USERNAME: admin
        DB_PASSWORD: admin
        QUEUE_CONNECTION: redis
        REDIS_HOST: 127.0.0.1
        REDIS_PASSWORD:
        REDIS_PORT: 6379
