name: PHPUnit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка зависимостей
      run: composer install --no-interaction

    - name: Копирование файла конфигурации для базы данных
      run: cp .env.testing .env

    - name: Генерация ключа приложения
      run: php artisan key:generate --ansi

    - name: Запуск тестов
      run: vendor/bin/phpunit
