name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Копирование .env.testing в .env
      run: cp .env.testing .env
    - name: Установка зависимостей Composer
      run: composer install
    - name: Установка необходимых прав для директорий
      run: chmod -R 777 storage bootstrap/cache
    - name: Генерация ключа шифрования
      run: php artisan key:generate
    - name: Запуск тестов
      run: ./vendor/bin/phpunit
